import type { Metadata } from "next";

import "./globals.css";
import Footer from "./components/Shared/Footer";
import Header from "./components/Shared/Header";

export const metadata: Metadata = {
  title: "MNA Web Programming",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
