import type { Metadata } from "next";

import "./globals.css";
import Footer from "./components/Shared/Footer";
import Header from "./components/Shared/Header";

export const metadata: Metadata = {
  title: "MNA Web Programming",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-b from-[#050d1a] to-[#0a1629] text-white">
        <Header />
        <div className="mt-10">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
